# Generated by Django 5.2.1 on 2025-06-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
